### ISSUE TITLE
Vega-lite not working with Julia 1.0.3?

### ISSUE THREAD

**Issue by gganapat** [fredo-dedup/VegaLite.jl#140]
Hi I'm having problems with Vega-Lite

In[xx] Pkg.add("VegaLite")
           using VegaLite

In[xx+1]: load("usa_cars.csv") |> 
               @vlplot(:point, x=:Miles_per_Gallon, y=:Weight_in_lbs)  

Output -------

module.js:549
    throw err;
    ^

Error: Cannot find module '../../deps/node_modules/vega-lite'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Gani/.julia/packages/VegaLite/J8uXC/src/rendering/compilesvg.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
VegaLite.VLSpec{:plot}
module.js:549
    throw err;
    ^

Error: Cannot find module '../../deps/node_modules/vega-lite'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Gani/.julia/packages/VegaLite/J8uXC/src/rendering/compilesvg.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by davidanthoff** [comment]
Could you try `]build VegaLite`` and report here what you get from that?

The error message indicates that something was not properly downloaded/installed...

**Comment by gganapat** [comment]
I forgot to update you. I deleted  VegaLite from packages and did a Pkg.add(“VetaLite”) and that fixed everything. Worked beautifully. Also, in your last email, I had to play around as key() didn’t work but key(_) worked fine.

Gani-
